/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as AuthActionRouteImport } from './routes/auth/action'
import { Route as ApiVerifyRecaptchaRouteImport } from './routes/api/verify-recaptcha'
import { Route as ApiSendNotificationRouteImport } from './routes/api/send-notification'
import { Route as ApiReleaseNotificationsCronRouteImport } from './routes/api/release-notifications-cron'
import { Route as ApiRebuildCacheRouteImport } from './routes/api/rebuild-cache'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiClientIpRouteImport } from './routes/api/client-ip'
import { Route as ApiArchiveRouteImport } from './routes/api/archive'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedMylistRouteImport } from './routes/_authenticated/mylist'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedForcePasswordRouteImport } from './routes/_authenticated/force-password'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as CollectionsStudiosIndexRouteImport } from './routes/collections/studios/index'
import { Route as CollectionsSeriesIndexRouteImport } from './routes/collections/series/index'
import { Route as CollectionsGenresIndexRouteImport } from './routes/collections/genres/index'
import { Route as CollectionsActressesIndexRouteImport } from './routes/collections/actresses/index'
import { Route as CollectionsStudiosStudioSlugRouteImport } from './routes/collections/studios/$studioSlug'
import { Route as CollectionsSeriesCodeSlugRouteImport } from './routes/collections/series/$codeSlug'
import { Route as CollectionsGenresGenreSlugRouteImport } from './routes/collections/genres/$genreSlug'
import { Route as CollectionsDirectorsDirectorSlugRouteImport } from './routes/collections/directors/$directorSlug'
import { Route as CollectionsActressesActorSlugRouteImport } from './routes/collections/actresses/$actorSlug'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person.$id'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => AuthRoute,
} as any)
const ApiVerifyRecaptchaRoute = ApiVerifyRecaptchaRouteImport.update({
  id: '/api/verify-recaptcha',
  path: '/api/verify-recaptcha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNotificationRoute = ApiSendNotificationRouteImport.update({
  id: '/api/send-notification',
  path: '/api/send-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseNotificationsCronRoute =
  ApiReleaseNotificationsCronRouteImport.update({
    id: '/api/release-notifications-cron',
    path: '/api/release-notifications-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRebuildCacheRoute = ApiRebuildCacheRouteImport.update({
  id: '/api/rebuild-cache',
  path: '/api/rebuild-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientIpRoute = ApiClientIpRouteImport.update({
  id: '/api/client-ip',
  path: '/api/client-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMylistRoute = AuthenticatedMylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForcePasswordRoute =
  AuthenticatedForcePasswordRouteImport.update({
    id: '/force-password',
    path: '/force-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CollectionsStudiosIndexRoute = CollectionsStudiosIndexRouteImport.update({
  id: '/collections/studios/',
  path: '/collections/studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSeriesIndexRoute = CollectionsSeriesIndexRouteImport.update({
  id: '/collections/series/',
  path: '/collections/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsGenresIndexRoute = CollectionsGenresIndexRouteImport.update({
  id: '/collections/genres/',
  path: '/collections/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsActressesIndexRoute =
  CollectionsActressesIndexRouteImport.update({
    id: '/collections/actresses/',
    path: '/collections/actresses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsStudiosStudioSlugRoute =
  CollectionsStudiosStudioSlugRouteImport.update({
    id: '/collections/studios/$studioSlug',
    path: '/collections/studios/$studioSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsSeriesCodeSlugRoute =
  CollectionsSeriesCodeSlugRouteImport.update({
    id: '/collections/series/$codeSlug',
    path: '/collections/series/$codeSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsGenresGenreSlugRoute =
  CollectionsGenresGenreSlugRouteImport.update({
    id: '/collections/genres/$genreSlug',
    path: '/collections/genres/$genreSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsDirectorsDirectorSlugRoute =
  CollectionsDirectorsDirectorSlugRouteImport.update({
    id: '/collections/directors/$directorSlug',
    path: '/collections/directors/$directorSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsActressesActorSlugRoute =
  CollectionsActressesActorSlugRouteImport.update({
    id: '/collections/actresses/$actorSlug',
    path: '/collections/actresses/$actorSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/tos': typeof TosRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/force-password': typeof AuthenticatedForcePasswordRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/mylist': typeof AuthenticatedMylistRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/rebuild-cache': typeof ApiRebuildCacheRoute
  '/api/release-notifications-cron': typeof ApiReleaseNotificationsCronRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/auth/action': typeof AuthActionRoute
  '/movies/$id': typeof MoviesIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/movies/': typeof MoviesIndexRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/collections/actresses/$actorSlug': typeof CollectionsActressesActorSlugRoute
  '/collections/directors/$directorSlug': typeof CollectionsDirectorsDirectorSlugRoute
  '/collections/genres/$genreSlug': typeof CollectionsGenresGenreSlugRoute
  '/collections/series/$codeSlug': typeof CollectionsSeriesCodeSlugRoute
  '/collections/studios/$studioSlug': typeof CollectionsStudiosStudioSlugRoute
  '/collections/actresses/': typeof CollectionsActressesIndexRoute
  '/collections/genres/': typeof CollectionsGenresIndexRoute
  '/collections/series/': typeof CollectionsSeriesIndexRoute
  '/collections/studios/': typeof CollectionsStudiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/tos': typeof TosRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/force-password': typeof AuthenticatedForcePasswordRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/mylist': typeof AuthenticatedMylistRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/rebuild-cache': typeof ApiRebuildCacheRoute
  '/api/release-notifications-cron': typeof ApiReleaseNotificationsCronRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/auth/action': typeof AuthActionRoute
  '/movies/$id': typeof MoviesIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/movies': typeof MoviesIndexRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/collections/actresses/$actorSlug': typeof CollectionsActressesActorSlugRoute
  '/collections/directors/$directorSlug': typeof CollectionsDirectorsDirectorSlugRoute
  '/collections/genres/$genreSlug': typeof CollectionsGenresGenreSlugRoute
  '/collections/series/$codeSlug': typeof CollectionsSeriesCodeSlugRoute
  '/collections/studios/$studioSlug': typeof CollectionsStudiosStudioSlugRoute
  '/collections/actresses': typeof CollectionsActressesIndexRoute
  '/collections/genres': typeof CollectionsGenresIndexRoute
  '/collections/series': typeof CollectionsSeriesIndexRoute
  '/collections/studios': typeof CollectionsStudiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/tos': typeof TosRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/force-password': typeof AuthenticatedForcePasswordRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/mylist': typeof AuthenticatedMylistRoute
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/client-ip': typeof ApiClientIpRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/rebuild-cache': typeof ApiRebuildCacheRoute
  '/api/release-notifications-cron': typeof ApiReleaseNotificationsCronRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/auth/action': typeof AuthActionRoute
  '/movies/$id': typeof MoviesIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/movies/': typeof MoviesIndexRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/collections/actresses/$actorSlug': typeof CollectionsActressesActorSlugRoute
  '/collections/directors/$directorSlug': typeof CollectionsDirectorsDirectorSlugRoute
  '/collections/genres/$genreSlug': typeof CollectionsGenresGenreSlugRoute
  '/collections/series/$codeSlug': typeof CollectionsSeriesCodeSlugRoute
  '/collections/studios/$studioSlug': typeof CollectionsStudiosStudioSlugRoute
  '/collections/actresses/': typeof CollectionsActressesIndexRoute
  '/collections/genres/': typeof CollectionsGenresIndexRoute
  '/collections/series/': typeof CollectionsSeriesIndexRoute
  '/collections/studios/': typeof CollectionsStudiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/search'
    | '/tos'
    | '/calendar'
    | '/explore'
    | '/force-password'
    | '/history'
    | '/mylist'
    | '/profiles'
    | '/settings'
    | '/stats'
    | '/api/archive'
    | '/api/client-ip'
    | '/api/proxy'
    | '/api/rebuild-cache'
    | '/api/release-notifications-cron'
    | '/api/send-notification'
    | '/api/verify-recaptcha'
    | '/auth/action'
    | '/movies/$id'
    | '/watch/$id'
    | '/movies/'
    | '/person/$id'
    | '/collections/actresses/$actorSlug'
    | '/collections/directors/$directorSlug'
    | '/collections/genres/$genreSlug'
    | '/collections/series/$codeSlug'
    | '/collections/studios/$studioSlug'
    | '/collections/actresses/'
    | '/collections/genres/'
    | '/collections/series/'
    | '/collections/studios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/search'
    | '/tos'
    | '/calendar'
    | '/explore'
    | '/force-password'
    | '/history'
    | '/mylist'
    | '/profiles'
    | '/settings'
    | '/stats'
    | '/api/archive'
    | '/api/client-ip'
    | '/api/proxy'
    | '/api/rebuild-cache'
    | '/api/release-notifications-cron'
    | '/api/send-notification'
    | '/api/verify-recaptcha'
    | '/auth/action'
    | '/movies/$id'
    | '/watch/$id'
    | '/movies'
    | '/person/$id'
    | '/collections/actresses/$actorSlug'
    | '/collections/directors/$directorSlug'
    | '/collections/genres/$genreSlug'
    | '/collections/series/$codeSlug'
    | '/collections/studios/$studioSlug'
    | '/collections/actresses'
    | '/collections/genres'
    | '/collections/series'
    | '/collections/studios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/offline'
    | '/privacy-policy'
    | '/search'
    | '/tos'
    | '/_authenticated/calendar'
    | '/_authenticated/explore'
    | '/_authenticated/force-password'
    | '/_authenticated/history'
    | '/_authenticated/mylist'
    | '/_authenticated/profiles'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/api/archive'
    | '/api/client-ip'
    | '/api/proxy'
    | '/api/rebuild-cache'
    | '/api/release-notifications-cron'
    | '/api/send-notification'
    | '/api/verify-recaptcha'
    | '/auth/action'
    | '/movies/$id'
    | '/watch/$id'
    | '/movies/'
    | '/_authenticated/person/$id'
    | '/collections/actresses/$actorSlug'
    | '/collections/directors/$directorSlug'
    | '/collections/genres/$genreSlug'
    | '/collections/series/$codeSlug'
    | '/collections/studios/$studioSlug'
    | '/collections/actresses/'
    | '/collections/genres/'
    | '/collections/series/'
    | '/collections/studios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  TosRoute: typeof TosRoute
  ApiArchiveRoute: typeof ApiArchiveRoute
  ApiClientIpRoute: typeof ApiClientIpRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiRebuildCacheRoute: typeof ApiRebuildCacheRoute
  ApiReleaseNotificationsCronRoute: typeof ApiReleaseNotificationsCronRoute
  ApiSendNotificationRoute: typeof ApiSendNotificationRoute
  ApiVerifyRecaptchaRoute: typeof ApiVerifyRecaptchaRoute
  MoviesIdRoute: typeof MoviesIdRoute
  WatchIdRoute: typeof WatchIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  CollectionsActressesActorSlugRoute: typeof CollectionsActressesActorSlugRoute
  CollectionsDirectorsDirectorSlugRoute: typeof CollectionsDirectorsDirectorSlugRoute
  CollectionsGenresGenreSlugRoute: typeof CollectionsGenresGenreSlugRoute
  CollectionsSeriesCodeSlugRoute: typeof CollectionsSeriesCodeSlugRoute
  CollectionsStudiosStudioSlugRoute: typeof CollectionsStudiosStudioSlugRoute
  CollectionsActressesIndexRoute: typeof CollectionsActressesIndexRoute
  CollectionsGenresIndexRoute: typeof CollectionsGenresIndexRoute
  CollectionsSeriesIndexRoute: typeof CollectionsSeriesIndexRoute
  CollectionsStudiosIndexRoute: typeof CollectionsStudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/verify-recaptcha': {
      id: '/api/verify-recaptcha'
      path: '/api/verify-recaptcha'
      fullPath: '/api/verify-recaptcha'
      preLoaderRoute: typeof ApiVerifyRecaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-notification': {
      id: '/api/send-notification'
      path: '/api/send-notification'
      fullPath: '/api/send-notification'
      preLoaderRoute: typeof ApiSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release-notifications-cron': {
      id: '/api/release-notifications-cron'
      path: '/api/release-notifications-cron'
      fullPath: '/api/release-notifications-cron'
      preLoaderRoute: typeof ApiReleaseNotificationsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rebuild-cache': {
      id: '/api/rebuild-cache'
      path: '/api/rebuild-cache'
      fullPath: '/api/rebuild-cache'
      preLoaderRoute: typeof ApiRebuildCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-ip': {
      id: '/api/client-ip'
      path: '/api/client-ip'
      fullPath: '/api/client-ip'
      preLoaderRoute: typeof ApiClientIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mylist': {
      id: '/_authenticated/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof AuthenticatedMylistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/force-password': {
      id: '/_authenticated/force-password'
      path: '/force-password'
      fullPath: '/force-password'
      preLoaderRoute: typeof AuthenticatedForcePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/collections/studios/': {
      id: '/collections/studios/'
      path: '/collections/studios'
      fullPath: '/collections/studios/'
      preLoaderRoute: typeof CollectionsStudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/series/': {
      id: '/collections/series/'
      path: '/collections/series'
      fullPath: '/collections/series/'
      preLoaderRoute: typeof CollectionsSeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/genres/': {
      id: '/collections/genres/'
      path: '/collections/genres'
      fullPath: '/collections/genres/'
      preLoaderRoute: typeof CollectionsGenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/actresses/': {
      id: '/collections/actresses/'
      path: '/collections/actresses'
      fullPath: '/collections/actresses/'
      preLoaderRoute: typeof CollectionsActressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/studios/$studioSlug': {
      id: '/collections/studios/$studioSlug'
      path: '/collections/studios/$studioSlug'
      fullPath: '/collections/studios/$studioSlug'
      preLoaderRoute: typeof CollectionsStudiosStudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/series/$codeSlug': {
      id: '/collections/series/$codeSlug'
      path: '/collections/series/$codeSlug'
      fullPath: '/collections/series/$codeSlug'
      preLoaderRoute: typeof CollectionsSeriesCodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/genres/$genreSlug': {
      id: '/collections/genres/$genreSlug'
      path: '/collections/genres/$genreSlug'
      fullPath: '/collections/genres/$genreSlug'
      preLoaderRoute: typeof CollectionsGenresGenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/directors/$directorSlug': {
      id: '/collections/directors/$directorSlug'
      path: '/collections/directors/$directorSlug'
      fullPath: '/collections/directors/$directorSlug'
      preLoaderRoute: typeof CollectionsDirectorsDirectorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/actresses/$actorSlug': {
      id: '/collections/actresses/$actorSlug'
      path: '/collections/actresses/$actorSlug'
      fullPath: '/collections/actresses/$actorSlug'
      preLoaderRoute: typeof CollectionsActressesActorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedForcePasswordRoute: typeof AuthenticatedForcePasswordRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMylistRoute: typeof AuthenticatedMylistRoute
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedForcePasswordRoute: AuthenticatedForcePasswordRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMylistRoute: AuthenticatedMylistRoute,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthActionRoute: typeof AuthActionRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActionRoute: AuthActionRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  TosRoute: TosRoute,
  ApiArchiveRoute: ApiArchiveRoute,
  ApiClientIpRoute: ApiClientIpRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiRebuildCacheRoute: ApiRebuildCacheRoute,
  ApiReleaseNotificationsCronRoute: ApiReleaseNotificationsCronRoute,
  ApiSendNotificationRoute: ApiSendNotificationRoute,
  ApiVerifyRecaptchaRoute: ApiVerifyRecaptchaRoute,
  MoviesIdRoute: MoviesIdRoute,
  WatchIdRoute: WatchIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  CollectionsActressesActorSlugRoute: CollectionsActressesActorSlugRoute,
  CollectionsDirectorsDirectorSlugRoute: CollectionsDirectorsDirectorSlugRoute,
  CollectionsGenresGenreSlugRoute: CollectionsGenresGenreSlugRoute,
  CollectionsSeriesCodeSlugRoute: CollectionsSeriesCodeSlugRoute,
  CollectionsStudiosStudioSlugRoute: CollectionsStudiosStudioSlugRoute,
  CollectionsActressesIndexRoute: CollectionsActressesIndexRoute,
  CollectionsGenresIndexRoute: CollectionsGenresIndexRoute,
  CollectionsSeriesIndexRoute: CollectionsSeriesIndexRoute,
  CollectionsStudiosIndexRoute: CollectionsStudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
